"""add_gcal_event_id_scheduled_at_pending_confirmation

Revision ID: 23f125e8246a
Revises: 1435d65c68e0
Create Date: 2026-05-22 17:05:46.556406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f125e8246a'
down_revision: Union[str, None] = '1435d65c68e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('gcal_event_id', sa.String(length=512), nullable=True))
    op.add_column('tasks', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('pending_confirmation', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_confirmation')
    op.drop_column('tasks', 'scheduled_at')
    op.drop_column('tasks', 'gcal_event_id')
    # ### end Alembic commands ###
